
name: Uptime Check

on:
  push:
    branches: [ "main" ]
    paths:
      - "urls.txt"
  workflow_dispatch: {}
name: Uptime

on:
  push:
    branches: [ "main" ]
    paths:
      - "urls.txt"
  workflow_dispatch: {}

concurrency:
  group: uptime-${{ github.ref }}
  cancel-in-progress: true


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run URL check
        run: |
          python scripts/url_check.py --input urls.txt --out reports/uptime.csv --retries 1 --timeout 8
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: uptime-report
          path: reports/uptime.csv
