
name: URL Uptime

on:
  push:
    branches: [ "main" ]
    paths:
      - "urls.txt"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: uptime-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # potrebno da bismo mogli da push-ujemo nazad

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run URL check
        run: |
          python check_urls.py

      - name: Commit report if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet -- report.md; then
            echo "No changes to commit."
          else
            git add report.md
            git commit -m "chore(ci): update report [skip ci]"
            git push
          fi

